# Site settings
title:          Jarett's Blog
description:    "Jarett's Blog for his developer stuff"
url:            "https://github.com/JarettRoman"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jarett Roman
  url:          https://github.com/JarettRoman
  email:        afrocious@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale